def raise_exception():
    raise TypeError("見つけた")
